/*
 * AUTOGENERATED BY /generate_schema_ts.js
 * DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING.
*/
export type ClientCommands =
  | {
      type: "CreateServer";
      [k: string]: unknown;
    }
  | {
      body: {
        communicator_type?: CommunicatorType | null;
        id: string;
        name?: string | null;
        [k: string]: unknown;
      };
      type: "UpdateServer";
      [k: string]: unknown;
    }
  | {
      body: number;
      type: "Increment";
      [k: string]: unknown;
    };

export enum CommunicatorType {
  None = "None",
  Test = "Test"
}

export type ServerCommands =
  | {
      type: "Identity";
      [k: string]: unknown;
    }
  | {
      body: ServerInfo[];
      type: "ServerInfo";
      [k: string]: unknown;
    }
  | {
      body: number;
      type: "Counter";
      [k: string]: unknown;
    };

export type CommunicatorStatus = "Disconnected" | "Connecting" | "Connected" | "Missing";

export interface ServerInfo {
  comm_status: CommunicatorStatus;
  comm_type: CommunicatorType;
  id: string;
  name: string;
  [k: string]: unknown;
}

export interface User {
  id: string;
  name: string;
  username: string;
  [k: string]: unknown;
}